version: "2.0"

services:


  bibcat:
    build: 
      context: ./
      dockerfile: ./bin/containers/Dockerfile
    ports:
      - 5000:5000

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false
    volumes:
      - "/opt/kean-concierge/search-index/eskean:/usr/share/elasticsearch/data"

  web:
    build:
      context: ./
      dockerfile: ./bin/containers/DockerfileNginx
    links:
     - bibcat:bibcat
    ports:
     - 80:80
     - 443:443
