version: "2.0"

services:

  bibcat:
    build: 
      context: ./
      dockerfile: ./bin/containers/Dockerfile
    ports:
      - 5000
    volumes:
      - instance:/opt/kean-concierge/instance 

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - "9200"
    environment:
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data

 
volumes:
  esdata:
    driver: local
  instance:
    driver: local
