version: "2.0"

services:

  bibcat:
    build: .
    ports:
      - 5000
    volumes:
      - instance:/opt/kean-concierge/instance 

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - "9200"
    environment:
#      - cluster.name=docker-clusteri
#      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data

 
volumes:
  esdata:
    driver: local
  instance:
    driver: local
