version: "2.0"

services:

  bibcat:
    image: .
    ports:
      - "5000"
    volumes:
      - instance:/opt/kean-concierge/instance 

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - "9200"
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  semanticServer:
    image: jermnelson/semantic-server-core:dev
    ports:
      - "8080"
      - "9999"
    volumes:
      - fedora:/opt/fedora/
      - triplestore:/opt/blazegraph
  

  web:
    build:
      context: .
      dockerfile: DockerfileNginx
    ports:
      - 80:80
      - 443:443
  
volumes:
  esdata:
    driver: local
  fedora:
    driver: local
  instance:
    driver: local
  triplestore:
    driver: local
